<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<?php
$appid=Mage::getStoreConfig('productlike_options/all_settings/fbappid');
$layout=Mage::getStoreConfig('productlike_options/all_settings/fblayout');
$face=Mage::getStoreConfig('productlike_options/all_settings/fbface');
$face=Mage::getStoreConfig('productlike_options/all_settings/fbface');
if($face==1){

    $face='true';
	
    }else{

    $face='false';

}
	
?>

<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like layout="<?php echo $layout; ?>" show_faces="<?php echo $face; ?>"   width="450" ></fb:like>








 

   